timeout: 1200s

images: ['eu.gcr.io/$PROJECT_ID/${_IMAGE}:${_TAG}']

options:
  sourceProvenanceHash: ['SHA256']

tags: ['${_IMAGE}', 'release', 'pypi']

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/${_IMAGE}:${_TAG}', '${_DOCKERFILE}']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/${_IMAGE}:${_TAG}']

substitutions:
  _IMAGE: pypi-gcs-proxy
  _TAG: latest
  _DOCKERFILE: .
