timeout: 1200s

images: ['eu.gcr.io/$PROJECT_ID/${_IMAGE}:${_TAG}']

options:
  sourceProvenanceHash: ['SHA256']

tags: ['${_IMAGE}', 'release', 'pypi']

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', '${_PYPI_GCS_PROXY_IMAGE}']

- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', '${_PYPI_GCS_PROXY_IMAGE}', 'eu.gcr.io/$PROJECT_ID/${_IMAGE}:${_TAG}']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/${_IMAGE}:${_TAG}']

substitutions:
  _IMAGE: 'pypi-gcs-proxy'
  _PYPI_GCS_PROXY_IMAGE: 'backupner/pypi-gcs-proxy:latest'
  _TAG: 'latest'
